### ISSUE TITLE
Syntax error on rfplayer.send command with DOMIA

### ISSUE THREAD

**Issue by loloweb06** [Doubledom45/HA_RFPLAYER#4]
Hello,

I have this error with this version. It does not occur with the original plugin. However, i do not get all entity with the original

service: rfplayer.send_command
data:
  automatic_add: false
  command: "OFF"
  protocol: DOMIA
  device_id: "237"

<img width="960" alt="image" src="https://github.com/Doubledom45/HA_RFPLAYER/assets/121865833/ffb96376-9b44-49cc-bd00-575916afa217">

To compare the syntax, it looks the command send is not following the same order.

With the original plugin, the log is the following and it works on the DOMIA plug
<img width="960" alt="Pasted Graphic" src="https://github.com/Doubledom45/HA_RFPLAYER/assets/121865833/f461bcf3-f51b-4e82-8885-6e4158dc4dbe">

Looking at the code, the issue looks to be here 👍  moving protocol before device id make it works on my Home assistant

(https://github.com/Doubledom45/HA_RFPLAYER/blob/67f6e49121cf3ac7591e4aa4d2383d31fb5316ee/custom_components/rfplayer/rflib/rfpprotocol.py#L199)

Corrections :

self.send_raw_packet(f"ZIA++{command} **{protocol} ID {device_id}** ") 
self.send_raw_packet(f"ZIA++{command} **{protocol} ID {device_id}** ")

**Comment by Doubledom45** [comment]
Salut..
# Permet d'avoir un ID qui représente le N° du Bp Limité au 256 premier ID (FIRMWARE)
```
## Test pour DOMIA ou chacon ID <256
            elif protocol == "DOMIA" or protocol == "CHACON" :
                    self.send_raw_packet(f"ZIA++{command} {device_id} {protocol}") # Permet d'avoir un ID qui représente le N° du Bp Limité au 256 premier ID (FIRMWARE)
            else :
                self.send_raw_packet(f"ZIA++{command} ID {device_id} {protocol}")

        elif device_address is not None:
            DIM_ADDON=""
            if command == "DIM" :
                DIM_ADDON="%50"
            self.send_raw_packet(f"ZIA++{command} {device_address} {protocol} {DIM_ADDON}")

        elif protocol == "EDISIOFRAME":
            self.send_raw_packet(f"ZIA++{protocol} {command}")
```
Version ne sera pas mise à jour , les envoies ne sont pas conformes !
