### ISSUE TITLE
Entity are not provided anymore after restart

### ISSUE THREAD

**Issue by loloweb06** [Doubledom45/HA_RFPLAYER#5]
Hello everyone,

An other issue. Entity are not enabled anymore after restarting. For sensor, it is OK as they are re detected. For Switch, it is more problematic. Here is the message.

<img width="579" alt="image" src="https://github.com/Doubledom45/HA_RFPLAYER/assets/121865833/656901b7-0be6-4a36-af78-0b5cefbee6f2">

To make it work, i replaced with the original 0.6 switch.py from GCE... and it looks to work, this is just a workaround to add entity.

**Comment by Doubledom45** [comment]
Salut..
Cela est fait pour pouvoir supprimer facilement les entités indésirables !
Une automation permet de recréer cette entité au redémarrage de HA !
Version ne sera pas mise à jour , voir version Test !

**Comment by loloweb06** [comment]
Oui, c est clair. Pour des sensors, pas de soucis, mais sur des switch 433, la seule facon de les ajouter est par l envoi de commande... manuel. Un peu genant. Donc ca a du sens sur les sensors, moins sur les capteurs.
