### ISSUE TITLE
Power in rfpparser.py

### ISSUE THREAD

**Issue by loloweb06** [Doubledom45/HA_RFPLAYER#6]
Hello,

There is a capital letter on Power in the rfpparser. Therefore the "power" entity on my OWL is not detected / added. Just replacing by "power" fixed it.

<img width="1203" alt="image" src="https://github.com/Doubledom45/HA_RFPLAYER/assets/121865833/269b4bde-0452-4308-86d5-a8acc66ed191">

[‎custom_components/rfplayer/rflib/rfpparser.py](https://github.com/Doubledom45/HA_RFPLAYER/blob/67f6e49121cf3ac7591e4aa4d2383d31fb5316ee/custom_components/rfplayer/rflib/rfpparser.py#L37)

"pow":"Power" to be changed in "power"

**Comment by Doubledom45** [comment]
OK 
[Modification](https://github.com/Doubledom45/HA_RFPLAYER/commit/422ccb88a7e032faf01d98ba31c610d4c819ee6e) 
Normalement cette version est obsolète car les commandes d'envoie ne sont pas conformes !
Voir version de test !
Merci

**Comment by loloweb06** [comment]
Merci
