### ISSUE TITLE
Improvement ; ajout des fonctions du configurateur java sur l'intégration HA

### ISSUE THREAD

**Issue by Jezza34000** [Doubledom45/HA_RFPLAYER#7]
Hello, 
Pas une issue mais plus une amélioration
Que pense tu de l'ajout des fonctions du configurateur sur l'intégration (Frequences/Selectivité/Sensibilité/etc.) ?
Perso ca me gonfle profondement le configurator en Java, et surtout ma clé est sur une VM sur mon NAS donc pour configurer je suis obliger de l'enlever, la mettre sur mon pc etc...
Je suis en train de regarder et essayer de comprende ton code pour voir comment ajouter ça, si tu as des pistes ou info je suis preneur.

**Comment by Jezza34000** [comment]
D'acc et du coup tu le fais comment dans la config en YAML y'a une doc dessus ?

**Comment by Doubledom45** [comment]
Je crois que j'ai montré un peu comment je fait dans la partie [discussion](https://github.com/Doubledom45/HA_RFPLAYER/discussions/1) voir la fin !
Tu peux faire la même chose pour n'importe quelle config dont tu as besoin !

Si tu es sous HA et sur le forum HA fr tu peux me contacter ! 
![image](https://github.com/Doubledom45/HA_RFPLAYER/assets/97252459/073b5fb0-a811-47e6-a7db-bc2d3ad37589)
